### ISSUE TITLE
Xiphos 0.3.25 SSE time forfeits - Chess GUI 40/2 round robin

### ISSUE THREAD

**Issue by yellow-panther** [milostatarevic/xiphos#11]
Hello Milos,
cf. game 6, 10, 21, 25, 54
[DEBUG.zip](https://github.com/milostatarevic/xiphos/files/2385499/DEBUG.zip)
[OUTPUT.zip](https://github.com/milostatarevic/xiphos/files/2385501/OUTPUT.zip)
[TOURNAMENTS.zip](https://github.com/milostatarevic/xiphos/files/2385502/TOURNAMENTS.zip)
[Xiphos logos.zip](https://github.com/milostatarevic/xiphos/files/2385503/Xiphos.logos.zip)

bitmap logos, edited with Photofiltre

**Comment by milostatarevic** [comment]
hi @yellow-panther, thanks for the report.

from the logs i see that the other engines also forfeited on time (with the same frequency). i'm suspicious that something is wrong with the setup.
