### ISSUE TITLE
Reports incorrect mate scores

### ISSUE THREAD

**Issue by mobmat** [milostatarevic/xiphos#15]
Solves "mate in" problems nicely, but reports the incorrect solution.
Mate in 10 problems are usually reported as M09, for example even if the PV shows a mate in 10.
Here is an example...a very easy problem for all engines
7K/P1p1p1p1/2P1P1Pk/6pP/3p2P1/1P6/3P4/8 w - - 2 1

**Comment by milostatarevic** [comment]
resolved here https://github.com/milostatarevic/xiphos/commit/016e9d06aaff581790e847623132f3618f792c7a
