### ISSUE TITLE
Misc. UCI output should use "info"

### ISSUE THREAD

**Issue by jdart1** [milostatarevic/xiphos#18]
Running the engine under python-chess produces the error:
<UciProtocol (pid=8848)>: Unexpected engine output: hash=16384MB

Output to the UCI driver that isn't a standard UCI command should be preceded by "info". For example:
`  _p("hash=%"PRIu64"MB\n", allocated_memory >> 20);`
in uci.cpp should be:
`  _p("info hash=%"PRIu64"MB\n", allocated_memory >> 20);`

**Comment by milostatarevic** [comment]
Thanks Jon, fixed here: https://github.com/milostatarevic/xiphos/commit/3086bd40d4a8340c0838694a5ef80fc838d44d49
