### ISSUE TITLE
Xiphos for android

### ISSUE THREAD

**Issue by Alexei1981** [milostatarevic/xiphos#2]
Hi.You can make the source code under Unix ?Then I could port the engine to Android(many ask).
Thanks.

**Comment by milostatarevic** [comment]
@Alexei1981 i've added no-popcnt support, so i hope that will help (check `make nopopcnt`)

**Comment by milostatarevic** [comment]
@Alexei1981 removed. could you try again?

**Comment by Alexei1981** [comment]
All going now,but there was another problem.Engine playing black doing a second course of flies,and white on the first move(it works,but when I try to make a move flies).
I had a similar problem with the engine written in C++ (Laser chess engine) and there was a problem with the command "position".The author corrected it and now everything is fine.

**Comment by milostatarevic** [comment]
@Alexei1981 i fixed the spacing issue, could you try again?

**Comment by Alexei1981** [comment]
Thanks.Now both versions (64-bit and 32-bit) work perfectly.
Only 32 bit incorrectly shows speed (> 300000 kns!!).
The 64 bit version shows the speed correctly.

**Comment by Alexei1981** [comment]
I removed the flag-flto and 32 bit version began to show speed=0.In this case, the engine works well and quickly gaining depth.

**Comment by milostatarevic** [comment]
@Alexei1981 i fixed the nodes counter. however, the 32-bit version performs poorly (nps is down almost 2.5x).

**Comment by Alexei1981** [comment]
Interestingly, the engine in the game mode works fine and plays hard.Well is gathering depth.
But in the analysis mode shows the depth of only 2-3 moves and no longer gaining.Include the analysis and it shows the depth of depth=4 and solidifies.

**Comment by milostatarevic** [comment]
at the moment, i don't have an easy fix for this. the engine doesn't respond to `stop` command, so even if it works, the analysis can't be interrupted. will implement this in future.
