### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GuardianRM** [milostatarevic/xiphos#4]
Good day. I would like to ask such a question. According to the statistics of large numbers, a sufficiently large sample can give fairly accurate results.
What is meant. Usually the standard chess program uses pst tables of 64 cells.
This allows the program to work quickly enough, replacing the table pst in the combination table 2-3 or more figures, we lose speed but increase the statistical sample, i.e. create a pseudo neural network. I would like to ask how you think this approach has a place or a slowdown of the program due to the use of the combination tables instead of pst will not have more positive effect !? 

There is also the assumption that it is possible to use separate pst tables for mobility, i.e.
table 8x8 for fields attacked by a particular figure or more extended Mobility table [count attacked squares][current square] can be useful.

Thanks.

**Comment by milostatarevic** [comment]
hi @GuardianRM, i don't think the speed is the issue here, but making it work properly.
i tried a couple of things here in the past (i also tried mobility tables), but without success.
this area is definitely worth exploring, but i doubt that anything simple will work easily.
