### ISSUE TITLE
Xiphos 0.3 does not stop

### ISSUE THREAD

**Issue by tissatussa** [milostatarevic/xiphos#8]
hi, i compiled your Xiphos 0.3 on Ubuntu 18.04 64-bit and i have some problems with it .. it runs, but does not do "go infinite" : it immediately comes up with a "best move" .. running it with "go movetime #" or "go depth #" works, but it can not be cancelled : it does not react to the stop command : it should cancel its calculations and give its best move so far ..

**Comment by milostatarevic** [comment]
please use the latest version from the repository (>= 0.3.15). `stop` and `go infinite` weren't supported back in 0.3.

**Comment by tissatussa** [comment]
i only find https://github.com/milostatarevic/xiphos and i compiled that "latest version 0.3" .. where is the repository >= 0.3.15 ?  Can you give the link ?

**Comment by milostatarevic** [comment]
after
```
git clone git@github.com:milostatarevic/xiphos.git
cd xiphos/
make
./xiphos-sse
```
it should report:
```
Xiphos 0.3.16 SSE by Milos Tatarevic
threads=1
hash=128MB
```
